import type { Metadata, ResolvingMetadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getLocale, getMessages, getTranslations } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

// export const metadata: Metadata = {
//   title: "Granint",
//   description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
  // const parentMetadata = await parent;
  // const local = await getLocale();
  const t = await getTranslations();

  return {
    title: t('app.metadata.title'),
    description: t('app.metadata.description'),
  };
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const local = await getLocale();

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={local}>
      {/* <head>
        <title>{t('metadata.title')}</title>
        <meta name="description" content={t('metadata.description')} />
      </head> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
